/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'base_practice' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32c0xx.h"

/* Keil::Device:Startup@1.0.0 */
#define RTE_DEVICE_STARTUP_STM32C0XX    /* Device Startup for STM32C0 */


#endif /* RTE_COMPONENTS_H */
